
export const countries = [
    {description: "Afghanistan", title: "Afghanistan", value: "AF"},
    {description: "Åland Islands", title: "Åland Islands", value: "AX"},
    {description: "Albania", title: "Albania", value: "AL"},
    {description: "Algeria", title: "Algeria", value: "DZ"},
    {description: "American Samoa", title: "American Samoa", value: "AS"},
    {description: "Andorra", title: "Andorra", value: "AD"},
    {description: "Angola", title: "Angola", value: "AO"},
    {description: "Anguilla", title: "Anguilla", value: "AI"},
    {description: "Antarctica", title: "Antarctica", value: "AQ"},
    {description: "Antigua and Barbuda", title: "Antigua and Barbuda", value: "AG"},
    {description: "Argentina", title: "Argentina", value: "AR"},
    {description: "Armenia", title: "Armenia", value: "AM"},
    {description: "Aruba", title: "Aruba", value: "AW"},
    {description: "Australia", title: "Australia", value: "AU"},
    {description: "Austria", title: "Austria", value: "AT"},
    {description: "Azerbaijan", title: "Azerbaijan", value: "AZ"},
    {description: "Bahamas", title: "Bahamas", value: "BS"},
    {description: "Bahrain", title: "Bahrain", value: "BH"},
    {description: "Bangladesh", title: "Bangladesh", value: "BD"},
    {description: "Barbados", title: "Barbados", value: "BB"},
    {description: "Belarus", title: "Belarus", value: "BY"},
    {description: "Belgium", title: "Belgium", value: "BE"},
    {description: "Belize", title: "Belize", value: "BZ"},
    {description: "Benin", title: "Benin", value: "BJ"},
    {description: "Bermuda", title: "Bermuda", value: "BM"},
    {description: "Bhutan", title: "Bhutan", value: "BT"},
    {description: "Bolivia", title: "Bolivia", value: "BO"},
    {description: "Bosnia and Herzegovina", title: "Bosnia and Herzegovina", value: "BA"},
    {description: "Botswana", title: "Botswana", value: "BW"},
    {description: "Bouvet Island", title: "Bouvet Island", value: "BV"},
    {description: "Brazil", title: "Brazil", value: "BR"},
    {description: "British Indian Ocean Territory", title: "British Indian Ocean Territory", value: "IO"},
    {description: "Brunei Darussalam", title: "Brunei Darussalam", value: "BN"},
    {description: "Bulgaria", title: "Bulgaria", value: "BG"},
    {description: "Burkina Faso", title: "Burkina Faso", value: "BF"},
    {description: "Burundi", title: "Burundi", value: "BI"},
    {description: "Cambodia", title: "Cambodia", value: "KH"},
    {description: "Cameroon", title: "Cameroon", value: "CM"},
    {description: "Canada", title: "Canada", value: "CA"},
    {description: "Cape Verde", title: "Cape Verde", value: "CV"},
    {description: "Cayman Islands", title: "Cayman Islands", value: "KY"},
    {description: "Central African Republic", title: "Central African Republic", value: "CF"},
    {description: "Chad", title: "Chad", value: "TD"},
    {description: "Chile", title: "Chile", value: "CL"},
    {description: "China", title: "China", value: "CN"},
    {description: "Christmas Island", title: "Christmas Island", value: "CX"},
    {description: "Cocos (Keeling) Islands", title: "Cocos (Keeling) Islands", value: "CC"},
    {description: "Colombia", title: "Colombia", value: "CO"},
    {description: "Comoros", title: "Comoros", value: "KM"},
    {description: "Congo", title: "Congo", value: "CG"},
    {description: "Congo, The Democratic Republic of", title: "The Democratic Republic of Congo", value: "CD"},
    {description: "Cook Islands", title: "Cook Islands", value: "CK"},
    {description: "Costa Rica", title: "Costa Rica", value: "CR"},
    {description: "Cote D'Ivoire", title: "Cote D'Ivoire", value: "CI"},
    {description: "Croatia", title: "Croatia", value: "HR"},
    {description: "Cuba", title: "Cuba", value: "CU"},
    {description: "Cyprus", title: "Cyprus", value: "CY"},
    {description: "Czech Republic", title: "Czech Republic", value: "CZ"},
    {description: "Denmark", title: "Denmark", value: "DK"},
    {description: "Djibouti", title: "Djibouti", value: "DJ"},
    {description: "Dominica", title: "Dominica", value: "DM"},
    {description: "Dominican Republic", title: "Dominican Republic", value: "DO"},
    {description: "Ecuador", title: "Ecuador", value: "EC"},
    {description: "Egypt", title: "Egypt", value: "EG"},
    {description: "El Salvador", title: "El Salvador", value: "SV"},
    {description: "Equatorial Guinea", title: "Equatorial Guinea", value: "GQ"},
    {description: "Eritrea", title: "Eritrea", value: "ER"},
    {description: "Estonia", title: "Estonia", value: "EE"},
    {description: "Ethiopia", title: "Ethiopia", value: "ET"},
    {description: "Falkland Islands (Malvinas)", title: "Falkland Islands (Malvinas)", value: "FK"},
    {description: "Faroe Islands", title: "Faroe Islands", value: "FO"},
    {description: "Fiji", title: "Fiji", value: "FJ"},
    {description: "Finland", title: "Finland", value: "FI"},
    {description: "France", title: "France", value: "FR"},
    {description: "French Guiana", title: "French Guiana", value: "GF"},
    {description: "French Polynesia", title: "French Polynesia", value: "PF"},
    {description: "French Southern Territories", title: "French Southern Territories", value: "TF"},
    {description: "Gabon", title: "Gabon", value: "GA"},
    {description: "Gambia", title: "Gambia", value: "GM"},
    {description: "Georgia", title: "Georgia", value: "GE"},
    {description: "Germany", title: "Germany", value: "DE"},
    {description: "Ghana", title: "Ghana", value: "GH"},
    {description: "Gibraltar", title: "Gibraltar", value: "GI"},
    {description: "Greece", title: "Greece", value: "GR"},
    {description: "Greenland", title: "Greenland", value: "GL"},
    {description: "Grenada", title: "Grenada", value: "GD"},
    {description: "Guadeloupe", title: "Guadeloupe", value: "GP"},
    {description: "Guam", title: "Guam", value: "GU"},
    {description: "Guatemala", title: "Guatemala", value: "GT"},
    {description: "Guernsey", title: "Guernsey", value: "GG"},
    {description: "Guinea", title: "Guinea", value: "GN"},
    {description: "Guinea-Bissau", title: "Guinea-Bissau", value: "GW"},
    {description: "Guyana", title: "Guyana", value: "GY"},
    {description: "Haiti", title: "Haiti", value: "HT"},
    {description: "Heard Island and Mcdonald Islands", title: "Heard Island and Mcdonald Islands", value: "HM"},
    {description: "Holy See (Vatican City State)", title: "Holy See (Vatican City State)", value: "VA"},
    {description: "Honduras", title: "Honduras", value: "HN"},
    {description: "Hong Kong", title: "Hong Kong", value: "HK"},
    {description: "Hungary", title: "Hungary", value: "HU"},
    {description: "Iceland", title: "Iceland", value: "IS"},
    {description: "India", title: "India", value: "IN"},
    {description: "Indonesia", title: "Indonesia", value: "ID"},
    {description: "Iran, Islamic Republic Of", title: "Iran, Islamic Republic Of", value: "IR"},
    {description: "Iraq", title: "Iraq", value: "IQ"},
    {description: "Ireland", title: "Ireland", value: "IE"},
    {description: "Isle of Man", title: "Isle of Man", value: "IM"},
    {description: "Israel", title: "Israel", value: "IL"},
    {description: "Italy", title: "Italy", value: "IT"},
    {description: "Jamaica", title: "Jamaica", value: "JM"},
    {description: "Japan", title: "Japan", value: "JP"},
    {description: "Jersey", title: "Jersey", value: "JE"},
    {description: "Jordan", title: "Jordan", value: "JO"},
    {description: "Kazakhstan", title: "Kazakhstan", value: "KZ"},
    {description: "Kenya", title: "Kenya", value: "KE"},
    {description: "Kiribati", title: "Kiribati", value: "KI"},
    {description: "Korea, Democratic People's Republic of", title: "Korea, Democratic People's Republic of", value: "KP"},
    {description: "Korea, South", title: "Korea, South", value: "KR"},
    {description: "Kuwait", title: "Kuwait", value: "KW"},
    {description: "Kyrgyzstan", title: "Kyrgyzstan", value: "KG"},
    {description: "Lao People's Democratic Republic", title: "Lao People's Democratic Republic", value: "LA"},
    {description: "Latvia", title: "Latvia", value: "LV"},
    {description: "Lebanon", title: "Lebanon", value: "LB"},
    {description: "Lesotho", title: "Lesotho", value: "LS"},
    {description: "Liberia", title: "Liberia", value: "LR"},
    {description: "Libyan Arab Jamahiriya", title: "Libyan Arab Jamahiriya", value: "LY"},
    {description: "Liechtenstein", title: "Liechtenstein", value: "LI"},
    {description: "Lithuania", title: "Lithuania", value: "LT"},
    {description: "Luxembourg", title: "Luxembourg", value: "LU"},
    {description: "Macao", title: "Macao", value: "MO"},
    {description: "Macedonia, The Former Yugoslav Republic of", title: "Macedonia, The Former Yugoslav Republic of", value: "MK"},
    {description: "Madagascar", title: "Madagascar", value: "MG"},
    {description: "Malawi", title: "Malawi", value: "MW"},
    {description: "Malaysia", title: "Malaysia", value: "MY"},
    {description: "Maldives", title: "Maldives", value: "MV"},
    {description: "Mali", title: "Mali", value: "ML"},
    {description: "Malta", title: "Malta", value: "MT"},
    {description: "Marshall Islands", title: "Marshall Islands", value: "MH"},
    {description: "Martinique", title: "Martinique", value: "MQ"},
    {description: "Mauritania", title: "Mauritania", value: "MR"},
    {description: "Mauritius", title: "Mauritius", value: "MU"},
    {description: "Mayotte", title: "Mayotte", value: "YT"},
    {description: "Mexico", title: "Mexico", value: "MX"},
    {description: "Micronesia, Federated States of", title: "Micronesia, Federated States of", value: "FM"},
    {description: "Moldova, Republic of", title: "Moldova, Republic of", value: "MD"},
    {description: "Monaco", title: "Monaco", value: "MC"},
    {description: "Mongolia", title: "Mongolia", value: "MN"},
    {description: "Montserrat", title: "Montserrat", value: "MS"},
    {description: "Morocco", title: "Morocco", value: "MA"},
    {description: "Mozambique", title: "Mozambique", value: "MZ"},
    {description: "Myanmar", title: "Myanmar", value: "MM"},
    {description: "Namibia", title: "Namibia", value: "NA"},
    {description: "Nauru", title: "Nauru", value: "NR"},
    {description: "Nepal", title: "Nepal", value: "NP"},
    {description: "Netherlands", title: "Netherlands", value: "NL"},
    {description: "Netherlands Antilles", title: "Netherlands Antilles", value: "AN"},
    {description: "New Caledonia", title: "New Caledonia", value: "NC"},
    {description: "New Zealand", title: "New Zealand", value: "NZ"},
    {description: "Nicaragua", title: "Nicaragua", value: "NI"},
    {description: "Niger", title: "Niger", value: "NE"},
    {description: "Nigeria", title: "Nigeria", value: "NG"},
    {description: "Niue", title: "Niue", value: "NU"},
    {description: "Norfolk Island", title: "Norfolk Island", value: "NF"},
    {description: "Northern Mariana Islands", title: "Northern Mariana Islands", value: "MP"},
    {description: "Norway", title: "Norway", value: "NO"},
    {description: "Oman", title: "Oman", value: "OM"},
    {description: "Pakistan", title: "Pakistan", value: "PK"},
    {description: "Palau", title: "Palau", value: "PW"},
    {description: "Palestinian Territory, Occupied", title: "Palestinian Territory, Occupied", value: "PS"},
    {description: "Panama", title: "Panama", value: "PA"},
    {description: "Papua New Guinea", title: "Papua New Guinea", value: "PG"},
    {description: "Paraguay", title: "Paraguay", value: "PY"},
    {description: "Peru", title: "Peru", value: "PE"},
    {description: "Philippines", title: "Philippines", value: "PH"},
    {description: "Pitcairn", title: "Pitcairn", value: "PN"},
    {description: "Poland", title: "Poland", value: "PL"},
    {description: "Portugal", title: "Portugal", value: "PT"},
    {description: "Puerto Rico", title: "Puerto Rico", value: "PR"},
    {description: "Qatar", title: "Qatar", value: "QA"},
    {description: "Reunion", title: "Reunion", value: "RE"},
    {description: "Romania", title: "Romania", value: "RO"},
    {description: "Russian Federation", title: "Russian Federation", value: "RU"},
    {description: "RWANDA", title: "RWANDA", value: "RW"},
    {description: "Saint Helena", title: "Saint Helena", value: "SH"},
    {description: "Saint Kitts and Nevis", title: "Saint Kitts and Nevis", value: "KN"},
    {description: "Saint Lucia", title: "Saint Lucia", value: "LC"},
    {description: "Saint Pierre and Miquelon", title: "Saint Pierre and Miquelon", value: "PM"},
    {description: "Saint Vincent and the Grenadines", title: "Saint Vincent and the Grenadines", value: "VC"},
    {description: "Samoa", title: "Samoa", value: "WS"},
    {description: "San Marino", title: "San Marino", value: "SM"},
    {description: "Sao Tome and Principe", title: "Sao Tome and Principe", value: "ST"},
    {description: "Saudi Arabia", title: "Saudi Arabia", value: "SA"},
    {description: "Senegal", title: "Senegal", value: "SN"},
    {description: "Serbia and Montenegro", title: "Serbia and Montenegro", value: "CS"},
    {description: "Seychelles", title: "Seychelles", value: "SC"},
    {description: "Sierra Leone", title: "Sierra Leone", value: "SL"},
    {description: "Singapore", title: "Singapore", value: "SG"},
    {description: "Slovakia", title: "Slovakia", value: "SK"},
    {description: "Slovenia", title: "Slovenia", value: "SI"},
    {description: "Solomon Islands", title: "Solomon Islands", value: "SB"},
    {description: "Somalia", title: "Somalia", value: "SO"},
    {description: "South Africa", title: "South Africa", value: "ZA"},
    {description: "South Georgia and the South Sandwich Islands", title: "South Georgia and the South Sandwich Islands", value: "GS"},
    {description: "Spain", title: "Spain", value: "ES"},
    {description: "Sri Lanka", title: "Sri Lanka", value: "LK"},
    {description: "Sudan", title: "Sudan", value: "SD"},
    {description: "Suridescription", title: "Suridescription", value: "SR"},
    {description: "Svalbard and Jan Mayen", title: "Svalbard and Jan Mayen", value: "SJ"},
    {description: "Swaziland", title: "Swaziland", value: "SZ"},
    {description: "Sweden", title: "Sweden", value: "SE"},
    {description: "Switzerland", title: "Switzerland", value: "CH"},
    {description: "Syrian Arab Republic", title: "Syrian Arab Republic", value: "SY"},
    {description: "Taiwan, Province of China", title: "Taiwan, Province of China", value: "TW"},
    {description: "Tajikistan", title: "Tajikistan", value: "TJ"},
    {description: "Tanzania, United Republic of", title: "Tanzania, United Republic of", value: "TZ"},
    {description: "Thailand", title: "Thailand", value: "TH"},
    {description: "Timor-Leste", title: "Timor-Leste", value: "TL"},
    {description: "Togo", title: "Togo", value: "TG"},
    {description: "Tokelau", title: "Tokelau", value: "TK"},
    {description: "Tonga", title: "Tonga", value: "TO"},
    {description: "Trinidad and Tobago", title: "Trinidad and Tobago", value: "TT"},
    {description: "Tunisia", title: "Tunisia", value: "TN"},
    {description: "Turkey", title: "Turkey", value: "TR"},
    {description: "Turkmenistan", title: "Turkmenistan", value: "TM"},
    {description: "Turks and Caicos Islands", title: "Turks and Caicos Islands", value: "TC"},
    {description: "Tuvalu", title: "Tuvalu", value: "TV"},
    {description: "Uganda", title: "Uganda", value: "UG"},
    {description: "Ukraine", title: "Ukraine", value: "UA"},
    {description: "United Arab Emirates", title: "United Arab Emirates", value: "AE"},
    {description: "United Kingdom", title: "United Kingdom", value: "GB"},
    {description: "United States", title: "United States", value: "US"},
    {description: "United States Minor Outlying Islands", title: "United States Minor Outlying Islands", value: "UM"},
    {description: "Uruguay", title: "Uruguay", value: "UY"},
    {description: "Uzbekistan", title: "Uzbekistan", value: "UZ"},
    {description: "Vanuatu", title: "Vanuatu", value: "VU"},
    {description: "Venezuela", title: "Venezuela", value: "VE"},
    {description: "Viet Nam", title: "Viet Nam", value: "VN"},
    {description: "Virgin Islands, British", title: "Virgin Islands, British", value: "VG"},
    {description: "Virgin Islands, U.S.", title: "Virgin Islands, U.S.", value: "VI"},
    {description: "Wallis and Futuna", title: "Wallis and Futuna", value: "WF"},
    {description: "Western Sahara", title: "Western Sahara", value: "EH"},
    {description: "Yemen", title: "Yemen", value: "YE"},
    {description: "Zambia", title: "Zambia", value: "ZM"},
    {description: "Zimbabwe", title: "Zimbabwe", value: "ZW"}
  ]
  